### ISSUE TITLE
Block Item Ids

### ISSUE THREAD

**Issue by ananinys** [AIPTU/BlockReplacer#11]
please make support for negative IDs so that I can use blocks in the plugin that work with ExtendedBlocks

**Comment by ananinys** [comment]
If it's easier to say, negative IDs don't work :(

**Comment by AIPTU** [comment]
@ananinys what have you tried before and what plugin did you use for it?

**Comment by ananinys** [comment]
> @ananinys что вы пробовали раньше и какой плагин вы для этого использовали?

i use vanilla blocks added thanks to ExtendedBlocks

**Comment by AIPTU** [comment]
What blocks have you tried before?
Make sure it matches this Ids
https://github.com/xSuperr/VanillaBlocks/blob/cbcca09a625f91af85cf6f06891ad85bb54c09b9/src/xSuper/VanillaBlocks/blocks/VanillaBlockIds.php#L7

**Comment by ananinys** [comment]
I wanted to check the plugin again, but it stopped working   :D                Error: "Class 'JackMD\ConfigUpdater\ConfigUpdater' not found" (EXCEPTION) in "plugins/BlockReplacer-master/src/aiptu/blockreplacer/BlockReplacer" at line 20

**Comment by AIPTU** [comment]
> I wanted to check the plugin again, but it stopped working :D Error: "Class 'JackMD\ConfigUpdater\ConfigUpdater' not found" (EXCEPTION) in "plugins/BlockReplacer-master/src/aiptu/blockreplacer/BlockReplacer" at line 20

Download from poggit

**Comment by ananinys** [comment]
id is written there BASALT = 489   but I checked and it does not work and I decided to find out the id and its id myself                                                                   BASALT = -234

**Comment by AIPTU** [comment]
> id is written there BASALT = 489 but I checked and it does not work and I decided to find out the id and its id myself BASALT = -234

is that work?

**Comment by ananinys** [comment]
> > там id написано BASALT = 489 но я проверил и он не работает и я решил сам узнать id и его id BASALT = -234
> 
> это работа?
basalt has an id of -234 and the plugin cannot interact with an id below 1. so clear? :)

**Comment by AIPTU** [comment]
I'll try to figure out a way for this since I have an idea about it for now

**Comment by ananinys** [comment]
> Я постараюсь найти способ для этого, так как пока у меня есть представление об этом.

 Thanks :)
