### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by PsychoNetworkDev** [AIPTU/BlockReplacer#13]
add compatibility with world protection plugins like worldprotect, bedcoreprotect, festival etc so we can make public mining areas where they can mine the certain blocks without mining blocks they arent supposed to be

**Comment by AIPTU** [comment]
Hi, thanks for the issue, you can try using this version [dev](https://poggit.pmmp.io/r/148576/BlockReplacer.phar), it support plugins like worldguard, worldguard etc.

**Comment by PsychoNetworkDev** [comment]
It wouldnt work for what i wanted it to do but no problem i made something myself
