### ISSUE TITLE
Suggetion

### ISSUE THREAD

**Issue by DaDevGuy** [AIPTU/BlockReplacer#14]
# Make It Work With Worlds

[ ] Please Make It Work With World Locked So We can Make A Mine

**Comment by AIPTU** [comment]
What plugin did you use to lock the world?

**Comment by DaDevGuy** [comment]
Worlds

**Comment by AIPTU** [comment]
Added 6d92625b33df02c8ce92a69e2c66a855b9a1c13d

**Comment by DaDevGuy** [comment]
Thanks
