### ISSUE TITLE
World protect bypass

### ISSUE THREAD

**Issue by Denon232** [AIPTU/BlockReplacer#15]
Your Plugin is not working on wp lock
Plzz make it that works on wp lock

**Comment by AIPTU** [comment]
/wp lock - nobody (even ops) is allowed to place/break blocks
/wp protect - players in the authorized list or, if the list is empty, players with wp.cmd.protect.auth permission can place/break blocks

**Comment by Denon232** [comment]
Bro dungeon Plugin work on wp lock

**Comment by AIPTU** [comment]
Have you tried using /wp protect instead of /wp lock?

**Comment by Denon232** [comment]
Yes, I did.

**Comment by AIPTU** [comment]
This worked fine for me when using both WorldProtect and Worlds plugins.
are you using version 1.5.0?
are you using version 1.5.0?

**Comment by Denon232** [comment]
Deops players are not able to break block
On world protect : on

**Comment by AIPTU** [comment]
I also tested it without op

**Comment by Denon232** [comment]
Ok, I'll check it out.
