### ISSUE TITLE
Regeneration is not working for non ops

### ISSUE THREAD

**Issue by LuciferVerma** [AIPTU/BlockReplacer#17]
If a non op player is breaking the blocks they are getting the the blocks instead of replacing it, but If a op player is breaking the block it works perfectly, it regens the block, but it's not working for non op players, 

I have a general ideas why it's happening, i think it's not working bc of bypass permission, but can you look into it.

And i have messed around some things and Found the solution. I just Removed ``` default: op``` in ```plugin.yml```

**Comment by AIPTU** [comment]
actually the block replacement is only for players who have permission, so not just any player can do it

**Comment by AIPTU** [comment]
You can give them permission using additional plugins like `PurePerms` or |GroupsAPI`

**Comment by LuciferVerma** [comment]
Ok thankyou for the help
