### ISSUE TITLE
[Suggetion] Add Per Block Replace Option

### ISSUE THREAD

**Issue by DaDevGuy** [AIPTU/BlockReplacer#18]
Please Add Per BLock Replace Option like i watn diamond ore to be replaced with bedrock and wood with air like this

**Comment by AIPTU** [comment]
Actually you can
https://github.com/AIPTU/BlockReplacer/blob/ed83ea6b87451b437223ddf84c1c9cc3ba086ea0/resources/config.yml#L18

**Comment by AIPTU** [comment]
https://github.com/AIPTU/BlockReplacer/blob/ed83ea6b87451b437223ddf84c1c9cc3ba086ea0/resources/config.yml#L21

**Comment by DaDevGuy** [comment]
ok
