### ISSUE TITLE
[Question] Do This Plugin Works 

### ISSUE THREAD

**Issue by DaDevGuy** [AIPTU/BlockReplacer#19]
Do This Plugin Works With Blocks Like Wheat And Beetroot To Replace With Air?

**Comment by AIPTU** [comment]
I haven't tried it yet, but you can try it

**Comment by DaDevGuy** [comment]
i tried it didnt worked

**Comment by AIPTU** [comment]
Can you show me your configuration?

**Comment by DaDevGuy** [comment]
i added - "wheat=air"

**Comment by AIPTU** [comment]
> i added - "wheat=air"

`"wheat_block=air"`

**Comment by AIPTU** [comment]
Sorry for the delay in replying

**Comment by DaDevGuy** [comment]
ok

**Comment by DaDevGuy** [comment]
worked
