### ISSUE TITLE
Bugs

### ISSUE THREAD

**Issue by Ibenrm** [AIPTU/BlockReplacer#4]
If you restart a server, task stop and can't replace block again, i know how to fix it

**Comment by AIPTU** [comment]
Feel free to open pull request

**Comment by Ibenrm** [comment]
You have discord ?, i can send example how to fix it

**Comment by AIPTU** [comment]
https://discord.gg/EggNF9hvGv

**Comment by AIPTU** [comment]
> If you restart a server, task stop and can't replace block again, i know how to fix it

I don't understand what you mean, the task will run if the player destroys the block and the task will stop if the server stops or according to cooldown
