### ISSUE TITLE
how to add crop like wheat or carrots 🥕 

### ISSUE THREAD

**Issue by ReakZzz** [AIPTU/BlockReplacer#49]

**Comment by ReakZzz** [comment]
How ?

**Comment by AIPTU** [comment]
You can use `wheat_block` or `carrot_block`

**Comment by ReakZzz** [comment]
Oh thank,  before me  use wheat:7 😅, let me try

**Comment by ReakZzz** [comment]
is not work 

My Config

"wheat_block:7=air=5":
      drops: []

**Comment by AIPTU** [comment]
What's doesn't work mean? do nothing?

**Comment by ReakZzz** [comment]
yes this doesn't work, but ore and block work

**Comment by AIPTU** [comment]
I'll investigate this

**Comment by ReakZzz** [comment]
Thank you and I will wait for you to finish it. ☺️

**Comment by AIPTU** [comment]
Confirmed this as a known bug and I will fix it in the next release.

**Comment by AIPTU** [comment]
Please try this build https://poggit.pmmp.io/r/220514/BlockReplacer.phar and let me know if it works, before I release it.

**Comment by ReakZzz** [comment]
Thank
