### ISSUE TITLE
Per blocks replace

### ISSUE THREAD

**Issue by chisi21** [AIPTU/BlockReplacer#5]
is it possible to replace a different block? like minecraft:gold_ore = minecraft:bedrock
minecraft:coal = minecraft:stone
minecraft:log = minecraft:planks

Thanks

**Comment by AIPTU** [comment]
Thanks for the suggestion, maybe per block replaced will be in the next version

**Comment by AIPTU** [comment]
Hi sorry a little late to tell you BlockReplacer now supports per block replaces and you can try it in this version https://poggit.pmmp.io/p/BlockReplacer/1.1.0 
if you found bug you can create issue, thanks.
